version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  node_modules:
    image: node:alpine
    volumes:
      - node_modules:/app/node_modules
volumes:
  node_modules:
